### PR TITLE
Add relay spindle

### PR DESCRIPTION
**Pull request by jimsynz**
Hi @Paciente8159.

Here's a simple change which adds a "relay spindle" which turns on and off digital pins when the spindle or coolant is enabled.

### CODE REVIEW

**Comment by Paciente8159** [comment]
Nice. 👍.
I'll take a better look in a couple of hours. If all check I'll merge it.

**Comment by Paciente8159** [comment]
Ok. Looks good to me. Just a couple of suggestions.
Instead of just 2 pins use 4 to allow users that also have a relay to invert the spindle dir and flood and mist controls.

```
#define SPINDLE_EN DOUT0
//if the spindle does not have and invert direction relay comment this line
#define SPINDLE_INV DOUT3
#define COOLANT_FLOOD DOUT1
#define COOLANT_MIST DOUT2

//if spindle does not have an invert direction relay this will make M4 work like M3
#ifndef SPINDLE_INV 
#define SPINDLE_INV SPINDLE_EN
#endif
```

Then you can change the set spindle to take invert in account. Also it's good when using mcu io directly functions to assert if the pin is defined. io_control function calls do that, but mcu io functions/macros don't, to allow better performance with direct register read and write accesses:

```
void spindle_relay_set_speed(uint8_t value, bool invert)
{

  if (value > 0)
  {
    if(!invert)
    {
#if !(SPINDLE_EN< 0)
        mcu_set_output(SPINDLE_EN);
#endif
    }
    else
    {
#if !(SPINDLE_INV< 0)
      mcu_set_output(SPINDLE_INV);
#endif
    }
  }
  else
  {
#if !(SPINDLE_EN< 0)
    mcu_clear_output(SPINDLE_EN);
#endif
#if !(SPINDLE_INV< 0)
    mcu_clear_output(SPINDLE_INV);
#endif
  }

  spindle_speed = value;
}```

On the set set_coolant callback just use the same has way as set in PWM spindle. If any of the coolant pins is not defined it will have no effect.

It's also possible to assign the same pin to both FLOOD and MIST to make M7 and M8 activate the same output for example if the user wants.

**Comment by jimsynz** [comment]
Thanks.  I’ll make these changes today.

**Comment by Paciente8159** [comment]
Just one more comment on my previous suggestion.
I've just noticed I forgot to disable the opposite relay prior to enable the desired relay or else both relays would be on.
It should be like this:

```
void spindle_relay_set_speed(uint8_t value, bool invert)
{

  if (value > 0)
  {
    if(!invert)
    {
#if !(SPINDLE_INV< 0)
      mcu_clear_output(SPINDLE_INV);
#endif
#if !(SPINDLE_EN< 0)
        mcu_set_output(SPINDLE_EN);
#endif
    }
    else
    {
#if !(SPINDLE_EN< 0)
        mcu_clear_output(SPINDLE_EN);
#endif
#if !(SPINDLE_INV< 0)
      mcu_set_output(SPINDLE_INV);
#endif
    }
  }
  else
  {
#if !(SPINDLE_EN< 0)
    mcu_clear_output(SPINDLE_EN);
#endif
#if !(SPINDLE_INV< 0)
    mcu_clear_output(SPINDLE_INV);
#endif
  }

  spindle_speed = value;
}
```

**Comment by Paciente8159** [comment]
My suggested code was wrong. The opposite relay must be turned off before turning the desired relay on.

```
void spindle_relay_set_speed(uint8_t value, bool invert)
{

  if (value > 0)
  {
    if(!invert)
    {
#if !(SPINDLE_INV< 0)
    mcu_clear_output(SPINDLE_INV);
#endif
#if !(SPINDLE_EN< 0)
        mcu_set_output(SPINDLE_EN);
#endif
    }
    else
    {
#if !(SPINDLE_EN< 0)
    mcu_clear_output(SPINDLE_EN);
#endif
#if !(SPINDLE_INV< 0)
      mcu_set_output(SPINDLE_INV);
#endif
    }
  }
  else
  {
#if !(SPINDLE_EN< 0)
    mcu_clear_output(SPINDLE_EN);
#endif
#if !(SPINDLE_INV< 0)
    mcu_clear_output(SPINDLE_INV);
#endif
  }

  spindle_speed = value;
}
```

**Comment by jimsynz** [comment]
@Paciente8159 I have made changes in the spirit of your suggestions.  Hopefully you approve.

**Pull request merged**
