### PR TITLE
Homing events

### PR DESCRIPTION
**Pull request by patryk3211**
This simple change adds two new events, `home_start` and `home_finish`. They are fired at the beginning and end of the homing sequence. The home finish event also has the error code as it's argument for the handler to check if homing was successful. In my case, I use these two events to extend and retract the Z probe which is also used as the Z limit.

### CODE REVIEW

**Comment by Paciente8159** [comment]
Thanks for your contribute. I'll give a look tomorrow and get back at you.
Just one question. Would it not be better to add the event at the motion controller home axis with the axis being homed, so that the deploy would only happen for the Z axis motion?

**Comment by patryk3211** [comment]
Yes I suppose that would be a better place for it, I'll make the changes as soon as I can.

**Comment by Paciente8159** [comment]
That sounds good. The [motion controller home axis](https://github.com/Paciente8159/uCNC/blob/cfa7a82a25a19c00087b8863df54f5e9b9a8170c/uCNC/src/core/motion_control.c#L688) as several exit points.
I think the best way to deal with it would be using a [__cleanup__ function](http://echorand.me/site/notes/articles/c_cleanup/cleanup_attribute_c.html) and then call the event from there passing the cleanup var as an arg to check if the homing was successful or not.

**Comment by patryk3211** [comment]
Done, now the event handlers receive a status struct instead of an array of values. Cleanup function is used to invoke the finish event, if it is run before it reaches the end of the homing sequence the status will be set to critical fail, at the end we set the status to OK just before cleanup is run.

**Comment by Paciente8159** [comment]
Spotless. Thanks for the contribute.

**Comment by Paciente8159** [comment]
Rolled out version [1.7.1](https://github.com/Paciente8159/uCNC/releases/tag/v1.7.1)

Again thanks for the contribution and feedback.

**Pull request merged**
