### PR TITLE
Add I2C speed configuration function

### PR DESCRIPTION
**Pull request by Paciente8159**
- Added I2C to all supporting architectures (all except 8266)

### CODE REVIEW

**Comment by Paciente8159** [comment]
I2C was also modified so it support Slave mode on some boards.
This will be used to run tests on multiboard capabilities.
Needs more in depth testing before integration

**Comment by Paciente8159** [comment]
I2C Slave needs to be reviewed.
Due to Slave requirements adopting Wire library for all architectures might be an more reliable option.
Baremetal performance is the trade off but in this case for the communication might be option.
Also due to Wire buffer size limitations on AVR baremetal code might be maintained on this architecture.

**Comment by Paciente8159** [comment]
All modifications are done and is ready for testing.

**Comment by patryk3211** [comment]
I'd like to suggest putting a simple if statement for an early break out of the loop if `I2C_SR1_AF` flag is set in [mcu_stm32f4x.c](https://github.com/Paciente8159/uCNC/blob/dfbe354a21d7c83eb7850c7369caacdc06a16e81/uCNC/src/hal/mcus/stm32f4x/mcu_stm32f4x.c#L965), the same thing can probably go in the stm32f1x file.

**Comment by patryk3211** [comment]
An even better idea might be to check for all three error conditions (`I2C_SR1_AF`, `I2C_SR1_ARLO` and `I2C_SR1_BERR`) of the STM32 I2C peripheral, this way we can avoid waiting for the full timeout when an error does happen.

**Comment by Paciente8159** [comment]
Thanks for the sugestions. I'll look into that tomorrow.
Actually I kind went a bit deep on this I2C issue because I was developing multiboard capabilities in parallel an I2C seemed to be a good candidate for this.
I've been running tests on AVR but the slave board seems to not ACK the master board.
I'll probably migrate the tests to STM32 to take advantage of debugging with a dap probe.

**Comment by Paciente8159** [comment]
The current I2C solution actually allow to be directly driven by the Arduino wire library (like for example done in the rp2040). I'm trying to avoid again for performance and resources questions. Running tests via this library is not out of the picture..

**Comment by patryk3211** [comment]
I've worked a bit more on the I2C of STM32F4 MCU and developed some basic error recovery which seems to handle bus error like lines getting stuck low pretty well. You can check it out at #407

**Comment by Paciente8159** [comment]
Super awesome. Thanks

**Comment by patryk3211** [comment]
No problem, always happy to help.

**Comment by Paciente8159** [comment]
I modified the callback so that the datalen argument is modified and sent back to the mcu ISR.
This way the correct data length to be sent in slave transmitter mode is knowned.
This way the last byte is transmitted with a NACK signalling the master that there is no more data to be sent and freeing the I2C bus.
Also fixed the STM32 error status checking and clearing masks.

**Comment by Paciente8159** [comment]
After some more careful reading of the atmega328p datasheet and removing some incorrect returns in the AVR ISR, slave I2C is working.
Minor fixes applied to STM32

**Comment by Paciente8159** [comment]
Although only tested on AVR will push changes since the basic concept is working. Any adaptation or fix required will most probably be at the architecture level

**Pull request merged**
