### PR TITLE
set default configuration options

### PR DESCRIPTION
**Pull request by etet100**
This is just a draft. I was wondering if these default options could be configurable for a specific machine.

### CODE REVIEW

**Comment by Paciente8159** [comment]
Yes they can. In an initial stage I kept them default to more or less match Grbl defaults but I also left them in h file to be able to customize it to a custom build.

LIMITS_INV_MASK was also separate from the settings itself (for some reason I don't recall) but I guess they could be merged too.

I'll review the changes and merge them if every thing seems ok.
Thanks.

**Comment by Paciente8159** [comment]
Ok. I after looking I think it would be better to make all the needed changes on the `defaults.h` file:

for example instead of having

`#define DEFAULT_STEP_PER_MM 200`

It would be like this

```
#ifndef DEFAULT_STEP_PER_MM
#define DEFAULT_STEP_PER_MM 200
#endif
```

in `config.h` or your custom boardmap you could then place

    /**
     * Override default configuration settings. Use _PER_AXIS parameters to
     * define different settings for each axis.
     * */

```
// #define DEFAULT_DIR_INV_MASK 2
// #define DEFAULT_LIMIT_INV_MASK 255
// #define DEFAULT_SOFT_LIMITS_ENABLED 1
// #define DEFAULT_HARD_LIMITS_ENABLED 1
// #define DEFAULT_HOMING_ENABLED 1
// #define DEFAULT_HOMING_DIR_INV_MASK 0
// #define DEFAULT_HOMING_FAST 2000
// #define DEFAULT_HOMING_SLOW 1500
// #define DEFAULT_HOMING_OFFSET 4
// #define DEFAULT_STEP_PER_MM 200
// #define DEFAULT_STEP_PER_MM_PER_AXIS {80, 144}
// #define DEFAULT_MAX_FEED 6000
// #define DEFAULT_MAX_FEED_PER_AXIS {6000, 6000}
// #define DEFAULT_ACCEL 1000
// #define DEFAULT_ACCEL_PER_AXIS {1000, 1000}
// #define DEFAULT_MAX_DIST 1000
// #define DEFAULT_MAX_DIST_PER_AXIS {420, 650}
```

Keeping the `DEFAULT_` prefix for all default settings makes the code easier to read.

Also this [line](https://github.com/etet100/uCNC/blob/0bee4b28db0d6ad8a3bbcb456ba4054f3874eddc/uCNC/src/interface/settings.c#L21) can be deleted since defaults.h is included in the correct order by cnc.h

**Review by Paciente8159 — CHANGES_REQUESTED** [review]
Please apply the needed modifications:

In `defaults.h` file:

For each default setting, for example instead of having

`#define DEFAULT_STEP_PER_MM 200`

It would be like this

```
#ifndef DEFAULT_STEP_PER_MM
#define DEFAULT_STEP_PER_MM 200
#endif
```
in config.h or your custom boardmap you could then place

```
/**
 * Override default configuration settings. Use _PER_AXIS parameters to
 * define different settings for each axis.
 * */
// #define DEFAULT_DIR_INV_MASK 2
// #define DEFAULT_LIMIT_INV_MASK 255
// #define DEFAULT_SOFT_LIMITS_ENABLED 1
// #define DEFAULT_HARD_LIMITS_ENABLED 1
// #define DEFAULT_HOMING_ENABLED 1
// #define DEFAULT_HOMING_DIR_INV_MASK 0
// #define DEFAULT_HOMING_FAST 2000
// #define DEFAULT_HOMING_SLOW 1500
// #define DEFAULT_HOMING_OFFSET 4
// #define DEFAULT_STEP_PER_MM 200
// #define DEFAULT_STEP_PER_MM_PER_AXIS {80, 144}
// #define DEFAULT_MAX_FEED 6000
// #define DEFAULT_MAX_FEED_PER_AXIS {6000, 6000}
// #define DEFAULT_ACCEL 1000
// #define DEFAULT_ACCEL_PER_AXIS {1000, 1000}
// #define DEFAULT_MAX_DIST 1000
// #define DEFAULT_MAX_DIST_PER_AXIS {420, 650}
```

Keeping the DEFAULT_ prefix for all default settings makes the code easier to read.

`settings.c` should reverted to the version in the master branch.

Thanks for your contribute. Please review the changes and I'll push the merge request.

**Comment by etet100** [comment]
I'm sorry. It wasn't my intention to make such confusion. I do not insint on merging my changes.

**Comment by Paciente8159** [comment]
All changes and suggestions are more then welcome and valid and I thank you for your contribute.
Having the defaults in the `cnc_config.h` (or at least overridable) makes all sense to make it easier to customize to a particular hardware.

I just have my point of view on how the code should be...and I do recognize I'm not always right and it's far from perfect.
I've just been spilling my guts into to this project for quite sometime now...and I've done my share of messed up code that after a while made me redo a ton of things.
My concerns with the code it's just because it costs time and sometimes the amount of changes are so big that they inevitably cause bugs and issues.

Keeping the changes in the `defaults.h` seemed to me the right choice because:
- As I said keeping the DEFAULT_ prefix makes the code easier to read
- There is an added bonus that it's easier with the help of intellisense and search to guess or find a particular value
- Avoids creating N other #defines

Your code seems good and ready for merge

**Review by Paciente8159 — APPROVED** [review]
All changes and suggestions are more then welcome and valid and I thank you for your contribute.
Having the defaults in the `cnc_config.h` (or at least overridable) makes all sense to make it easier to customize to a particular hardware.

I just have my point of view on how the code should be...and I do recognize I'm not always right and it's far from perfect.
I've just been spilling my guts into to this project for quite sometime now...and I've done my share of messed up code that after a while made me redo a ton of things.
My concerns with the code it's just because it costs time and sometimes the amount of changes are so big that they inevitably cause bugs and issues.

Keeping the changes in the `defaults.h` seemed to me the right choice because:
- As I said keeping the DEFAULT_ prefix makes the code easier to read
- There is an added bonus that it's easier with the help of intellisense and search to guess or find a particular value
- Avoids creating N other #defines

Your code seems good and ready for merge

**Pull request merged**
