### PR TITLE
allow multiple chained JOG commands

### PR DESCRIPTION
**Pull request by Paciente8159**
- allow multiple chained JOG commands

### CODE REVIEW

**Comment by etet100** [comment]
Am I doing something wrong?
```
13:34:14: $J=G1 X100 Y100 F1000
13:34:14: ok
13:34:15: $J=G1 X200 Y200
13:34:15: error:8 (Idle Error) << IS THIS CORRECT?
13:34:15: ok
```

**Comment by Paciente8159** [comment]
Don't include the g1. You don't set the motion command on jog command. Internally g1 is used.

**Comment by Paciente8159** [comment]
And by the way I tested your commands. You should be getting an error 16 not and error 8. Did you downloaded the correct branch?

**Comment by etet100** [comment]
Actually it doesn't matter whether i use g1 or not. It works (both commands are executed) but i'm not sure what this error 8 means. It is misleading and seems to be incorrect.

**Comment by Paciente8159** [comment]
There is a list of errors on the wiki but you can also check the error codes [here](https://github.com/Paciente8159/uCNC/blob/ee8f20ec475af78597628a1ee05f9f7d01036fb5/uCNC/src/interface/grbl_interface.h#L52)

**Comment by Paciente8159** [comment]
> Actually it doesn't matter whether i use g1 or not. It works (both commands are executed) but i'm not sure what this error 8 means. It is misleading and seems to be incorrect.

In this case yes. It's an error to define the motion command if sending a JOG command. JOG implicitly uses G1 under the hood.
Also note that this is also mentioned in the [Grbl jogging wiki entry](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Jogging#how-to-use)

**Comment by etet100** [comment]
I'm sorry but i'm not convinced. 
```
17:44:38: $J=X100 Y100 F400
17:44:38: ok
17:44:41: $J=X100 Y10 F400
17:44:41: error:8 (Idle Error) << error again
17:44:41: ok
```
and
`$J=G91 G20 X0.5 F10`
should be perfectly fine too. 
`$J=G91 G20 X0.5 F10 will move +0.5 inches (12.7mm) to X=22.7mm (WPos) at a feed rate of 10. Note that G91 and G20 are only applied to this jog command.`

Error 8 is IDLE ERROR. I don't see any mention of this error in context of the jogging feature.

**Comment by Paciente8159** [comment]
> I'm sorry but i'm not convinced.
> 
> ```
> 17:44:38: $J=X100 Y100 F400
> 17:44:38: ok
> 17:44:41: $J=X100 Y10 F400
> 17:44:41: error:8 (Idle Error) << error again
> 17:44:41: ok
> ```
> 
> and `$J=G91 G20 X0.5 F10` should be perfectly fine too. `$J=G91 G20 X0.5 F10 will move +0.5 inches (12.7mm) to X=22.7mm (WPos) at a feed rate of 10. Note that G91 and G20 are only applied to this jog command.`
> 
> Error 8 is IDLE ERROR. I don't see any mention of this error in context of the jogging feature.

Jog is only allowed if the machine is either in the idle or jog state. That error also exists in grbl.

Grbl states that besides g20/g21 g90/g91 and g53

> All other g-codes, m-codes, and value words (including S and T) are not accepted in the jog command.

Are you using the UNO or other board?

**Comment by etet100** [comment]
Arduino Nano.

I believe It is in jog state. I'm sending two subsequent jogging commands. 

I will compile grbl and check it myself.

**Comment by Paciente8159** [comment]
Ok I'm getting that error too. But I was not getting it in the simulator. Investigating

**Comment by Paciente8159** [comment]
The problem was that the JOG flag was (sometimes) being cleared after the first jog command.
This would cause the state of the motion to change from JOG to RUN. Then next command would then throw that error because JOG commands expect the cnc state to be in either the JOG or IDLE state.

**Pull request merged**
